### ISSUE TITLE
Union types

### ISSUE THREAD

**Issue by AlexGalays** [ooesili/type-safe-json-decoder#1]
Hello and great job !

I couldn't find how to decode string union types and have the decoder actually checks the value is one of the strings in the union? Do you have an example?

**Comment by etaque** [comment]
Could be something like :

``` typescript
type Easing = "ease-in" | "ease-out" | "ease-in-out";

const easingDecoder: Decoder<Easing> = andThen(string(), s => {
  return oneOf(equal("ease-in"), equal("ease-out"), equal("ease-in-out"), fail("Unable to decode easing"));
});
```

**Comment by ooesili** [comment]
Hmm. I hadn't thought about it. @etaque has a good suggestion. 

A couple nitpicks though, you don't need the `andThen` since `s` isn't used. Also, `fail` doesn't strictly need to be here, (`oneOf` already fails by default), but it can be used to add better error messages.

``` typescript
type Easing = "ease-in" | "ease-out" | "ease-in-out"

const easingDecoder: Decoder<Easing> = oneOf(
  equal("ease-in"),
  equal("ease-out"),
  equal("ease-in-out")
)
```

I'll for sure add this to the docs somewhere once we figure out the best way.

**Comment by AlexGalays** [comment]
Won't typescript refuse to cast the right hand side `Decoder<string>` to the left hand side `Decode<Easing>` ? You could easily forget about a few enum cases too.

**Comment by ooesili** [comment]
In retrospect, I probably should have ran my code through the compiler first :blush:. This is the best that I could come up with the existing library.

``` typescript
export type Easing = "ease-in" | "ease-out" | "ease-in-out"

export const easingDecoder: Decoder<Easing> = oneOf(
  equal("ease-in" as Easing),
  equal("ease-out" as Easing),
  equal("ease-in-out" as Easing)
)
```

This also prevents us from misspelling any of strings the `equal` decoders.

As for making sure that you specify every type, I have a few ideas. We could add something like this:

``` typescript
function union <A>(ad: Decoder<A>): Decoder<A>
function union <A, B>(ad: Decoder<A>, bd: Decoder<B>): Decoder<A | B>
function union <A, B, C>(ad: Decoder<A>, bd: Decoder<B>, cd: Decoder<C>): Decoder<A | B | C>
// ...
```

Then, we could do this:

``` typescript
export type Easing = 'ease-in' | 'ease-out' | 'ease-in-out'

export const easingDecoder: Decoder<Easing> = union(
  equal('ease-in' as 'ease-in'),
  equal('ease-out' as 'ease-out'),
  equal('ease-in-out' as 'ease-in-out')
)
```

However, nothing would stop us from forgetting an `equal` case if we added a new string to `Easing`, as subsets are assignable to their supersets.

The best that I can come up with right now (just before midnight on a Monday) is this:

``` typescript
// add this to the Decoder class
get type(): T {
  throw new Error(`don't actually use me`)
}

export const easingDecoder = union(
  equal('ease-in' as 'ease-in'),
  equal('ease-out' as 'ease-out'),
  equal('ease-in-out' as 'ease-in-out')
)

export type Easing = typeof easingDecoder.type
```

Using TypeScript's "type queries", we could define our actual type as being calculated from the Decoder, then we have a single source of truth for our enum values. Now if we forget a value, other parts of our code will break, so we'll know at build time.

**Comment by ooesili** [comment]
I pushed up 5eabfa8 which adds the `union` function that I mentioned above. @AlexGalays let me know if you have any thoughts what I did, I want to make sure that it meets your needs.

**Comment by AlexGalays** [comment]
Looks good !

**Comment by ooesili** [comment]
Perfect. I'll close this issue once I tag a release with this commit in it :)

**Comment by ooesili** [comment]
Just pushed v0.1.0 to here and npm with this feature
