### ISSUE TITLE
Allow extension of Decoders

### ISSUE THREAD

**Issue by nahgrin** [ooesili/type-safe-json-decoder#17]
The current API is closed to extension, making it difficult to solve some situations.  It would be nice if the Decoder class was opened for extension, possibly by making the constructor public, to allow end users to make their own decoders.

I can write up a PR for this, but I would like to see if this is a feature that has interest in being added first.

**Comment by kunimitaiyoh** [comment]
+1.

**Comment by ooesili** [comment]
I'd rather keep the constructor private. Creating new decoders involves dealing with `any` quite a bit and that's something I'd like to keep out of this package's API.

I think some of TypeScript's newer features will help this package get past some of its current limitations. If there are specific problems that you have in mind please raise them.
