### ISSUE TITLE
Decode method for arbitrary Javascript objects

### ISSUE THREAD

**Issue by MazeChaZer** [ooesili/type-safe-json-decoder#2]
Right now, it is only possible to decode JSON strings using `Decoder.decodeJSON()`. An additional general public `decode()` method on `Decoder` that takes a Javascript object of type `any` would be useful. In my use case, another library returns a Javascript object that I would like to decode.

**Comment by ooesili** [comment]
This won't be too hard, but I want to make sure we get the name right. I'm not sure if the word `decode` is the best this function. Would `validate` or `verify` make more sense? My thinking is that we are not really changing the input, we're simply adding types and making sure that the object conforms to those types.

On the other hand, `Decoder.validate` doesn't make as much sense as `Decoder.decode` in general, and `decode` would be pretty easy to understand if you saw the type signature.

My contenders:
- `Decoder.decode`
- `Decoder.decodeJS`
- `Decoder.decodeAny`
- `Decoder.verify`
- `Decoder.validate`

**Comment by MazeChaZer** [comment]
I like `Decoder.decodeAny`. If I see a function named `verify` or `validate` I would expect it to return a boolean, but I see where you're coming from.

**Comment by ooesili** [comment]
Cool. I went with `decodeAny`. I'm going to push out a new release (as soon as I remember how to publish npm packages 😊)

**Comment by ooesili** [comment]
Just pushed v0.1.0 to here and npm with this feature

**Comment by MazeChaZer** [comment]
Great :+1:

**Comment by radix** [comment]
fwiw, the docs for the new decodeAny are incorrect: if you use things like the `map` function, it doesn't just verify your data and return it unmodified, it can also transform it. I use this to great effect in my decoders.

**Comment by ooesili** [comment]
@radix Good point. I'll try to fix that up tomorrow. A PR would also be welcome if you have a good way of wording it 😄
