### ISSUE TITLE
Lazy decoder for recursive structures

### ISSUE THREAD

**Issue by MazeChaZer** [ooesili/type-safe-json-decoder#4]
http://package.elm-lang.org/packages/elm-lang/core/5.0.0/Json-Decode#lazy

**Comment by ooesili** [comment]
That one took me a minute to understand what it was even for, haha. I pushed up 1e57b57 to a development branch. I'll merge it and tag a release once #2 is resolved.

**Comment by MazeChaZer** [comment]
Great :+1:

**Comment by ooesili** [comment]
Just pushed v0.1.0 to here and npm with this feature
